export const EMAIL_FILLED = 'EMAIL_FILLED'
export const RESET_REQUEST = 'RESET_REQUEST'
export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_FAILED = 'RESET_FAILED'
export const EMAIL_CHECK = "EMAIL_CHECK_FORGOT"