export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const POST_NOTIFICATION = 'POST_NOTIFICATION'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const READ_NOTIFICATION = 'READ_NOTIFICATION'